[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/getall"
  to = "/.netlify/functions/get"
  status = 200

[[redirects]]
  from = "/get/:params"
  to = "/.netlify/functions/get?license=:params"
  status = 200

[[redirects]]
  from = "/get/*"
  to = "/.netlify/functions/get"
  status = 200

