[build]
  functions = "netlify/functions"
  publish = "."

# Return all records
[[redirects]]
  from = "/getall"
  to = "/.netlify/functions/get"
  status = 200

# Redirect all /get/* to one function handler
[[redirects]]
  from = "/get/*"
  to = "/.netlify/functions/get"
  status = 200
