[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/getall"
  to = "/.netlify/functions/get"
  status = 200

[[redirects]]
  from = "/get/*"
  to = "/.netlify/functions/get/:splat"
  status = 200
  force = true

[functions]
  included_files = ["data.json"]
