[build]
  functions = "netlify/functions"
  publish = "."

# Return all records
[[redirects]]
  from = "/getall"
  to = "/.netlify/functions/get"
  status = 200

# Single license using wildcard path
[[redirects]]
  from = "/get/*"
  to = "/.netlify/functions/get"
  status = 200
